### ISSUE TITLE
Message update text does not take into account keys with underscores in them

### ISSUE THREAD

**Issue by marknotfound** [marknotfound/jcr#1]
Converting the changeset key from `snake_case` to a normal human-readable text does not take into account underscores and instead just uppercases the underscored key name. For example `start_time` becomes `Start_time`. Underscores should be replaced with spaces and all words uppercased (e.g. `start_time` becomes `Start Time`)
![image](https://user-images.githubusercontent.com/1442186/178790788-d3a1386b-c2c9-48b8-b47b-a3f80889cc1d.png)

**Comment by RubanJaganathan** [comment]
hey , i would like to do this.

**Comment by marknotfound** [comment]
Closed by https://github.com/marknotfound/jcr/pull/2
